collaborator: c2 #name of collaborator 
sources: 
  - name: s1
    csv_location: c2_s1_loc
    description: table having data for c2_s1 
    columns:
      - name: col1 
        type: string
        masking_type: sha256
    transformation_owners_allowed:
      - c1
    destinations_allowed: 
      - ref: /c3/destination/d1
        noise_parameters: 
          - epsilon: ln3 
          - delta: 1e-5