collaborator: collab3 #name of collaborator 
sources: 
  - name: collab3_table
    csv_location: ./collab3_location_csv.csv
    description: table having data for collab3 
    columns:
      - name: email 
        type: string
        masking_type: sha256
        selectable: true # can you run select query on this col
        aggregates_allowed: # no other aggregates are to be allowed. 
          - aggregate2
          - aggregate4  
        join_key: true # can this column be used as a join_key
    consumers_allowed: # who is allowed to use this source in transformation
      - collab1
    destinations_allowed: 
      - ref: /collab1/transformation/collab3_transformation 
        noise_parameters: 
          - epsilon: ln3 
          - delta: 1e-5
          - kappa: 1
          - threshold: between 0 and 3  