collaborator: Airline #name of collaborator 
tables: 
  - name: Airline_Customers
    csv_location: ./airline_customers.csv
    description: table having data for airline customers
    consumers_allowed: # who is allowed to write transformations on my sources. 
      - research
    columns:
      - name: email 
        type: string
        masking_type: sha256
        selectable: false # can you run select query on this col
        aggregates_allowed: # no other aggregates are to be allowed. 
          - private_count
          - private_count_distinct  
        join_key: true # can this column be used as a join_key
      - name: phone_number # if aggregates_allowed not mentioned assume aggregates not allowed. 
        type: string 
        masking_type: sha256
        selectable: false
        aggregates_allowed: none
        join_key: true 
      - name: zip 
        type: string 
        selectable: true
        aggregates_allowed: 
          - count 
        masking_type: none
        join_key: false 
      - name: pets
        type: string 
        masking_type: none
        aggregates_allowed: 
          - count
        selectable: true
        join_key: true
destinations_allowed: 
  - ref: /Research/transformation/private_total_customers 
    tables_allowed: 
      - /Media/source/media_customers 
    noise_parameters: 
      - epsilon: ln3 
      - delta: 1e-5
      - kappa: 1
      - threshold: between 0 and 3  